### ISSUE TITLE
argus query fails with "cannot execute job <> when phase = COMPLETED"

### ISSUE THREAD

**Issue by SharonGoliath** [opencadc/cadctools#209]
Traceback (most recent call last):
  File "/Users/goliaths/Library/Python/3.12/lib/python/site-packages/cadcutils/net/ws.py", line 1040, in check_status
    response.raise_for_status()
  File "/Users/goliaths/Library/Python/3.12/lib/python/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/luskan/sync/igib6gg9cjq1w70i/run

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Development/dev/scripts/tap_counts.py", line 89, in <module>
    main()
  File "/Volumes/Development/dev/scripts/tap_counts.py", line 82, in main
    si = _do_si(client)
         ^^^^^^^^^^^^^^
  File "/Volumes/Development/dev/scripts/tap_counts.py", line 45, in _do_si
    t = _run_query(qs, client).to_pandas()
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Development/dev/scripts/tap_counts.py", line 16, in _run_query
    client.query(
  File "/Users/goliaths/Library/Python/3.12/lib/python/site-packages/cadctap/core.py", line 407, in query
    with self._tap_client.post(resource, params=fields,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/goliaths/Library/Python/3.12/lib/python/site-packages/cadcutils/net/ws.py", line 334, in post
    return session.post(self._get_url(resource), verify=self.verify, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/goliaths/Library/Python/3.12/lib/python/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/goliaths/Library/Python/3.12/lib/python/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/goliaths/Library/Python/3.12/lib/python/site-packages/cadcutils/net/ws.py", line 1026, in send
    response = super(RetrySession, self).send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/goliaths/Library/Python/3.12/lib/python/site-packages/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/goliaths/Library/Python/3.12/lib/python/site-packages/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
           ^^^^^^^^^^
  File "/Users/goliaths/Library/Python/3.12/lib/python/site-packages/cadcutils/net/ws.py", line 984, in send
    self.check_status(response)
  File "/Users/goliaths/Library/Python/3.12/lib/python/site-packages/cadcutils/net/ws.py", line 1049, in check_status
    raise exceptions.BadRequestException(orig_exception=e)
cadcutils.exceptions.BadRequestException: cannot execute job igib6gg9cjq1w70i when phase = COMPLETED

**Comment by andamian** [comment]
`cadctap` runs sync queries which are single access URLs and this error occurs when the request returns and intermittent error or it times out). The client should prevent the session from re-trying on this URLs and either report the error to the user (especially in the more typical case of timeouts) or re-try the query from the beginning.
